### ISSUE TITLE
Any list of good examples / best practices?

### ISSUE THREAD

**Issue by fabm22** [thekua/grunt-regex-check#13]
Hi, 

sorry if this is not really a issue.

I wonder if you guys would know a list of typical good regexp in JavaScript projects in teams ???

Thanks a lot

**Comment by mmouterde** [comment]
Lint tools generally already include rules to avoid typical language errors.

For regEx rules : just learn from your mistakes : if a you met a bug, failed a demo and it could be avoided with a regex check : add a rule.

Basically, I'm looking for `console.xxx(` for memory leak, `localhost` from demo fail or static IP due to prod bug...

Depending on your own coding rules, your framework, you can watch for issue : Ex with AngularJS, a regex warn if a dev use $http in Controllers.

**Comment by fabm22** [comment]
Hi, thx for answer @mmouterde 
So yeah this was also the idea I had, exactly. Building progressively and depending of projects requirements, some regexp useful as a "in the background" constant check.

For your example, AngularJS, you might be aware of this eslint plugin that kinda does just that, like forthe $http in Controllers warning : 

https://github.com/Gillespie59/eslint-plugin-angular
